### ISSUE TITLE
如果第三方被混淆了的情况呢？

### ISSUE THREAD

**Issue by Neacy** [dinuscxj/ClassPlugin#1]
如题  :
被混淆的文件  我们就无法知道源码  这种情况该如何替换旧的class    求思路。
Thanks..

**Comment by dinuscxj** [comment]
被混淆的代码是同样处理的方式， 把对应的class 替换掉就可以， 这个处理是在混淆之前处理的 
比如你所引用的jar 里面有一个类混淆过是a.class,  但是你发现a.class有问题， 就创建一个a.java,  a.java 的包名也要和jar里面的包名一样， 然后把a.class 在andriod studio 里面的java内容拷贝到a.java中， 然后修改bug， 然后rebuild 项目， 就会生成一个a.class
